### ISSUE TITLE
Error: " ORA-00904: "CUSTOMER"."GEO_LOCATION": invalid identifier" when accessing geo location 

### ISSUE THREAD

**Issue by janis-kra** [ADFCommunityDE/AltaUI#8]
When trying to use the geo location (latitude or longitude) in the thematic map, i get this error on page load. Any thoughts on this?

<img width="1050" alt="screen shot 2015-09-29 at 08 50 21" src="https://cloud.githubusercontent.com/assets/8240324/10157084/3a6b729a-6687-11e5-94bb-d0af805161f2.png">

Also, I need the coordinates to be Doubles, not Strings. Is it enough to change the type in the entity object to Double?

**Comment by janis-kra** [comment]
Bug occurs in this commit: https://github.com/ADFCommunityDE/AltaUI/commit/d2ad37fed2046c0ceb4c3bcb44116f7b4b65cc19

**Comment by mketeam** [comment]
Please try to drop the user summit_adf from your local database and execute the build script again. To get the coordinates as doubles, we need to alter the S_GEO_COORDINATES_data.sql and the create tables script, where the column types have to be changed to number instead of varchar2.

Unfortunately, I do not have access to github source repository right now.

**Comment by janis-kra** [comment]
That worked, thanks, thought I already did that. Got another problem now with the coordinates, but that's another issue.
